Avoid cargo 1.43–1.45 in GitHub Actions
These versions are incompatible with some recent GitHub change.

    error: failed to get `rustversion` as a dependency of package `dyn-clone v1.0.8 (/home/runner/work/dyn-clone/dyn-clone)`

    Caused by:
      failed to load source for dependency `rustversion`

    Caused by:
      Unable to update registry `https://github.com/rust-lang/crates.io-index`

    Caused by:
      failed to fetch `https://github.com/rust-lang/crates.io-index`

    Caused by:
      error reading from the zlib stream; class=Zlib (5)